src/Alix.WebTester/ViewModels/Equipment/FirstTestViewModel.cs
namespace Alix.WebTester.ViewModels.Equipment
{
    using System.Collections.Generic;
    using Alix.Core.Interfaces;

    public class FirstTestViewModel
    {
        public IPlayer Player { get; set; }
        public IList<IEquipment> Equipment { get; set; }
        public int ChosenEquipmentId { get; set; }
    }
}

src/Alix.WebTester/Controllers/EquipmentController.cs
namespace Alix.WebTester.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Alix.WebTester.ViewModels.Equipment;

    public class EquipmentController : Controller
    {
        public ActionResult Index()
        {
            return this.View();
        }

        public ActionResult UnEquip(int equipmentId)
        {
            var chosenEquipment = Equipment.FirstTest.Equipment.First(x => x.Id == equipmentId);
            Equipment.FirstTest.Player.UnEquip(chosenEquipment.Slot);

            return this.RedirectToAction("FirstTest");
        }

        public ActionResult Equip(int equipmentId)
        {
            var chosenEquipment = Equipment.FirstTest.Equipment.First(x => x.Id == equipmentId);
            Equipment.FirstTest.Player.Equip(chosenEquipment);

            return this.RedirectToAction("FirstTest");
        }

        public ActionResult FirstTest()
        {
            var viewModel = new FirstTestViewModel
            {
                Player = Equipment.FirstTest.Player,
                Equipment = Equipment.FirstTest.Equipment
            };

            return this.View(viewModel);
        }
    }
}

src/Alix.WebTester/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Alix.WebTester.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Alix.WebTester/Views/Equipment/FirstTest.cshtml
@model Alix.WebTester.ViewModels.Equipment.FirstTestViewModel

@{
    ViewBag.Title = "First Test";
}

<h2>Player</h2>
<ul>
    <li>
        <strong>Current Hit Points:</strong>
        <ul>
            <li>Base: @Model.Player.CurrentHitPoints.GetBase()</li>
            <li>Value: @Model.Player.CurrentHitPoints.Get()</li>
        </ul>
    </li>
    <li>
        <strong>Maximum Hit Points:</strong>
        <ul>
            <li>Base: @Model.Player.MaximumHitPoints.GetBase()</li>
            <li>Value: @Model.Player.MaximumHitPoints.Get()</li>
        </ul>
    </li>
    <li>
        <strong>Current Magic Points:</strong>
        <ul>
            <li>Base: @Model.Player.CurrentMagicPoints.GetBase()</li>
            <li>Value: @Model.Player.CurrentMagicPoints.Get()</li>
        </ul>
    </li>
    <li>
        <strong>Maximum Magic Points:</strong>
        <ul>
            <li>Base: @Model.Player.MaximumMagicPoints.GetBase()</li>
            <li>Value: @Model.Player.MaximumMagicPoints.Get()</li>
        </ul>
    </li>
    <li>
        <strong>Strength:</strong>
        <ul>
            <li>Base: @Model.Player.Strength.GetBase()</li>
            <li>Value: @Model.Player.Strength.Get()</li>
        </ul>
    </li>
    <li>
        <strong>Speed:</strong>
        <ul>
            <li>Base: @Model.Player.Speed.GetBase()</li>
            <li>Value: @Model.Player.Speed.Get()</li>
        </ul>
    </li>
    <li>
        <strong>Intelligence:</strong>
        <ul>
            <li>Base: @Model.Player.Intelligence.GetBase()</li>
            <li>Value: @Model.Player.Intelligence.Get()</li>
        </ul>
    </li>
    <li>
        <strong>Equipment:</strong>
        <ul>
            @foreach (var equipment in Model.Player.Equipment)
            {
                <li>@equipment.Value.Name</li>
            }
        </ul>
    </li>
</ul>

<h2>Available Equipment</h2>

<div class="row">
    @foreach (var equipment in Model.Equipment)
    {
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">@equipment.Name</h1>
                </div>
                <div class="panel-body">
                    <ul>
                        <li><strong>Id:</strong> @equipment.Id</li>
                        <li><strong>Slot:</strong> @equipment.Slot</li>
                        <li>
                            <strong>Addition Modifiers:</strong>
                            <ul>
                                @foreach (var modifier in equipment.AdditionModifiers)
                                {
                                    <li>@modifier.Key @modifier.Value.OutputValue</li>
                                }
                            </ul>
                        </li>
                        <li>
                            <strong>Multiply Modifiers:</strong>
                            <ul>
                                @foreach (var modifier in equipment.MultiplyModifiers)
                                {
                                    <li>@modifier.Key @modifier.Value.OutputValue</li>
                                }
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="panel-footer text-center">
                    @if (Model.Player.IsEquipped(equipment))
                    {
                        using (Html.BeginForm("UnEquip", "Equipment"))
                        {
                            @Html.Hidden("equipmentId", equipment.Id)
                            <button type="submit" class="btn btn-default">Un-Equip</button>
                        }
                    }
                    else
                    {
                        using (Html.BeginForm("Equip", "Equipment"))
                        {
                            @Html.Hidden("equipmentId", equipment.Id)
                            <button type="submit" class="btn btn-default">Equip</button>
                        }
                    }
                </div>
            </div>
        </div>
    }
</div>

src/Alix.WebTester/Views/Equipment/Index.cshtml
@{
    ViewBag.Title = "Equipment Tests";
}

<h2>title</h2>

src/Alix.WebTester/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Alix.WebTester/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Alix.WebTester/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/Alix.WebTester/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Equipment <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("First Test", "FirstTest", "Equipment")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>